### ISSUE TITLE
Fonts are to small on high DPI

### ISSUE THREAD

**Issue by razvanab** [kmkolasinski/AwesomeBump#35]
Fonts are too small when using high DPI settings in windows

![Example Image](http://i.imgur.com/ntabjqi.jpg)

**Comment by kmkolasinski** [comment]
Hi, ok I will add option to change the font size in new releases.

**Comment by Terrance8D** [comment]
Hi, I don't think this is an issue. In 3.0, the font size was scaled down from 12 pts to 10 pts. There's no way to change the font size in AwesomeBump itself, but you can change that in the code.

**Comment by kmkolasinski** [comment]
Yeah sure this is not an issue, but rather a small feature request :)

**Comment by kmkolasinski** [comment]
Solved in Pi version.

**Comment by ryobg** [comment]
![1](https://user-images.githubusercontent.com/13996376/99141182-537f7300-2651-11eb-8b1b-b86942fb6d44.jpg)

I think this is not fixed. Tried with 5.1 for Windows, can't find an way to increase the font size in any way (damn qt). Tried with the config setting for font size, but it does nothing?

**Comment by Calinou** [comment]
@ryobg Does it improve if you right-click the application, choose **Properties > Compatibility** and force the application scaling mode to **System**? This will be blurry/pixelated, but at least it should be usable.

**Comment by ryobg** [comment]
@Calinou Actually it did improved a bit! I played with these settings before posting, but this one for some reasons I haven't touched. It is kind of a bit bigger and blurry. Still... I would say it is better if there was a setting to tune up the font, button size, whatever...
